# Generated by Django 6.0 on 2026-01-04 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='idle', max_length=50),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма списания', max_digits=8)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('billing_date', models.DateField(help_text='Дата следующего списания')),
                ('remind_days_before', models.PositiveIntegerField(default=3, help_text='За сколько дней напоминать')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='bot.user')),
            ],
        ),
    ]
