# Generated by Django 6.0 on 2026-01-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_user_state_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
