# Generated by Django 6.0 on 2026-01-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_subscription_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='username',
            new_name='name',
        ),
    ]
